export {
  DOCUMENT_OWNER_TYPES,
  type DocumentOwnerType,
  type ExpiryRule,
  DOCUMENT_TYPES,
  EXPIRING_WINDOW_DAYS,
  type DocumentStatus,
  DOCUMENT_STATUSES,
  type RevisionStatus,
  isOwnerType,
  isDocumentStatus,
  isDocumentType,
  MAX_LIST_LIMIT,
  DEFAULT_LIST_LIMIT,
  MIN_DATE,
  MAX_EXPIRY_DATE,
  NO_EXPIRY_KEY,
  type DocumentRevision,
  type Document,
  type RevisionData,
  type NewDocumentData,
  type DocumentPatch,
  type Expiry,
  type ExpiryFilter,
} from './types.js';
export { type DocumentErrorCode, type DocumentConflictField, DocumentError } from './errors.js';
export {
  requireOpaqueId,
  requireVersion,
  dateOf,
  addDays,
  normalizeDocumentNumber,
  REVISION_FIELDS,
  CREATE_FIELDS,
  UPDATE_FIELDS,
  parseNewDocument,
  parseRenewal,
  parseDocumentPatch,
} from './validation.js';
export {
  expiryKeyOf,
  expiryOf,
  revisionStatus,
  expiryFilterOf,
  matchesExpiry,
  revisionOf,
  newDocument,
  applyPatch,
  applyRenewal,
  applyArchive,
} from './rules.js';
export {
  type DocumentFilter,
  type DocumentWindow,
  type DocumentSlice,
  type DocumentRevisionSlice,
  type DocumentStore,
  type DocumentOwnerGate,
} from './ports.js';
export { InMemoryDocumentStore } from './store.js';
export {
  type DocumentListQuery,
  type DocumentHistoryQuery,
  type DocumentServiceOptions,
  DocumentService,
} from './service.js';
