import 'reflect-metadata';
import { describe, expect, it, vi } from 'vitest';
import { DataSource, type QueryRunner, type Table } from 'typeorm';
import {
  SETTINGS_ENTITIES,
  SETTINGS_TABLES,
  SettingsEntity,
  BINARY_COLLATION,
} from './entities.js';
import {
  SETTINGS_CHECKS,
  SETTINGS_MIGRATIONS_TABLE,
  SETTINGS_MIGRATION_VERSION,
  CreateCompanySettings2026100600090,
} from './migrations.js';
import {
  SETTINGS_RUNTIME_ACCOUNT,
  createSettingsDataSource,
  createSettingsMigrationDataSource,
  runSettingsMigrations,
} from './data-source.js';

const migration = new CreateCompanySettings2026100600090();

function recordingRunner() {
  const tables: Table[] = [];
  const statements: string[] = [];
  const dropped: string[] = [];
  const runner = {
    createTable: async (table: Table) => {
      tables.push(table);
    },
    dropTable: async (name: string) => {
      dropped.push(name);
    },
    query: async (sql: string) => {
      statements.push(sql);
      return [];
    },
  } as unknown as QueryRunner;
  return { runner, tables, statements, dropped };
}

describe('migration and entity metadata agree', () => {
  it('creates the settings table and drops it again (reversible), with the next migration id', async () => {
    const { runner, tables, dropped } = recordingRunner();
    await migration.up(runner);
    expect(tables.map((table) => table.name)).toEqual([SETTINGS_TABLES.settings]);
    await migration.down(runner);
    expect(dropped).toEqual([SETTINGS_TABLES.settings]);
    expect(migration.name).toBe('CreateCompanySettings2026100600090');
    expect(migration.name.endsWith(SETTINGS_MIGRATION_VERSION)).toBe(true);
    expect(SETTINGS_MIGRATION_VERSION).toMatch(/^\d{13}$/);
    // The next id after the assignments migration (2026100600080).
    expect(Number(SETTINGS_MIGRATION_VERSION)).toBe(2026100600080 + 10);
  });

  it('declares every column of the entity with the same type, size, nullability and collation', async () => {
    const { runner, tables } = recordingRunner();
    await migration.up(runner);
    const dataSource = new DataSource({
      type: 'mysql',
      database: 'synthetic',
      entities: [...SETTINGS_ENTITIES],
      synchronize: false,
    });
    await (dataSource as unknown as { buildMetadatas(): Promise<void> }).buildMetadatas();
    const entity = dataSource.entityMetadatas[0];
    const table = tables[0] as Table;
    expect(entity?.tableName).toBe(table.name);
    expect(entity?.columns.map((column) => column.databaseName).sort()).toEqual(
      table.columns.map((column) => column.name).sort(),
    );
    for (const column of table.columns) {
      const mapped = entity?.columns.find((candidate) => candidate.databaseName === column.name);
      if (!mapped) throw new Error(`no column ${column.name}`);
      const label = column.name;
      expect([label, mapped.type]).toEqual([label, column.type]);
      expect([label, String(mapped.length || '')]).toEqual([label, column.length || '']);
      expect([label, mapped.isPrimary]).toEqual([label, column.isPrimary]);
      expect([label, mapped.isNullable]).toEqual([label, column.isNullable]);
      expect([label, mapped.unsigned ?? false]).toEqual([label, column.unsigned ?? false]);
      expect([label, mapped.collation ?? null]).toEqual([label, column.collation ?? null]);
      expect([label, mapped.precision ?? null]).toEqual([label, column.precision ?? null]);
      if (column.type === 'varchar')
        expect([label, column.collation]).toEqual([label, BINARY_COLLATION]);
    }
    expect(table.columns.filter((column) => column.isPrimary).map((c) => c.name)).toEqual([
      'company_id',
    ]);
    expect(table.columns.every((column) => !column.isNullable)).toBe(true);
    expect(table.foreignKeys).toEqual([]);
  });

  it('adds NULL-safe CHECK constraints as raw DDL after the table exists', async () => {
    const { runner, statements } = recordingRunner();
    await migration.up(runner);
    expect(statements).toHaveLength(SETTINGS_CHECKS.length);
    for (const check of SETTINGS_CHECKS)
      expect(statements).toContain(
        `ALTER TABLE \`${check.table}\` ADD CONSTRAINT \`${check.name}\` CHECK (${check.expression})`,
      );
    for (const check of SETTINGS_CHECKS) expect(check.expression).toContain('IS TRUE');
    const text = SETTINGS_CHECKS.map((check) => check.expression).join('\n');
    expect(text).toContain('`expiry_window_days` BETWEEN 1 AND 30');
    expect(text).toContain('pii_reader');
  });
});

describe('DDL generated by the real MySQL query runner', () => {
  it('emits the binary collation, the company primary key and InnoDB', async () => {
    const dataSource = new DataSource({
      type: 'mysql',
      database: 'synthetic',
      entities: [...SETTINGS_ENTITIES],
      synchronize: false,
    });
    const runner = dataSource.driver.createQueryRunner('master') as QueryRunner & {
      getCurrentDatabase(): Promise<string>;
    };
    const statements: string[] = [];
    runner.query = (async (sql: string) => {
      statements.push(sql);
      return [];
    }) as typeof runner.query;
    runner.getCurrentDatabase = async () => 'synthetic';
    await migration.up(runner);
    const ddl = statements.filter((sql) => sql.startsWith('CREATE TABLE'));
    expect(ddl).toHaveLength(1);
    expect(ddl[0]).toContain('PRIMARY KEY (`company_id`)');
    expect(ddl[0]).toContain('`company_id` varchar(64) COLLATE "utf8mb4_0900_bin" NOT NULL');
    expect(ddl[0]).toContain('`expiry_window_days` tinyint UNSIGNED NOT NULL');
    expect(ddl[0]).toContain('`version` int UNSIGNED NOT NULL');
    expect(ddl[0]).toContain('ENGINE=InnoDB');
    expect(ddl[0]).not.toMatch(/ON DELETE|ON UPDATE|CASCADE/);
    expect(statements.filter((sql) => sql.startsWith('ALTER TABLE'))).toHaveLength(
      SETTINGS_CHECKS.length,
    );
  });
});

describe('DataSource factories', () => {
  const base = {
    host: '127.0.0.1',
    port: 3306,
    database: 'opslog_settings',
    password: 'synthetic',
  };

  it('creates a pooled runtime DataSource for a restricted account only', () => {
    const dataSource = createSettingsDataSource({ ...base, username: 'opslog_settings_runtime' });
    expect(dataSource.options).toMatchObject({
      type: 'mysql',
      synchronize: false,
      migrationsRun: false,
      logging: false,
      timezone: 'Z',
      charset: 'utf8mb4',
      migrationsTableName: SETTINGS_MIGRATIONS_TABLE,
      migrationsTransactionMode: 'all',
      connectTimeout: 10_000,
      extra: { connectionLimit: 10, waitForConnections: true, queueLimit: 100 },
    });
    const tuned = createSettingsDataSource({
      ...base,
      username: 'opslog_settings_runtime',
      connectionLimit: 3,
      queueLimit: 7,
      connectTimeoutMs: 500,
    });
    expect(tuned.options).toMatchObject({
      connectTimeout: 500,
      extra: { connectionLimit: 3, queueLimit: 7 },
    });
    for (const username of ['root', 'admin', 'opslog_assignments_x', 'opslog_settings_', ''])
      expect(() => createSettingsDataSource({ ...base, username })).toThrow(
        /restricted runtime account/,
      );
    expect(SETTINGS_RUNTIME_ACCOUNT.test('opslog_settings_abc123')).toBe(true);
    expect(dataSource.options.entities).toHaveLength(SETTINGS_ENTITIES.length);
  });

  it('creates a migration DataSource that is never used at runtime', () => {
    const dataSource = createSettingsMigrationDataSource({ ...base, username: 'schema_owner' });
    expect(dataSource.options).toMatchObject({
      type: 'mysql',
      synchronize: false,
      migrationsRun: false,
      logging: false,
      migrationsTableName: SETTINGS_MIGRATIONS_TABLE,
    });
    expect(dataSource.options.migrations).toEqual([CreateCompanySettings2026100600090]);
    const custom = createSettingsMigrationDataSource({
      ...base,
      username: 'schema_owner',
      connectTimeoutMs: 42,
    });
    expect(custom.options).toMatchObject({ connectTimeout: 42 });
  });

  it('runs migrations in one transaction and refuses unsafe options', async () => {
    const runMigrations = vi.fn(async () => []);
    await runSettingsMigrations({
      options: { type: 'mysql', synchronize: false, migrationsRun: false },
      runMigrations,
    } as unknown as DataSource);
    expect(runMigrations).toHaveBeenCalledExactlyOnceWith({ transaction: 'all' });
    for (const options of [{ synchronize: true }, { migrationsRun: true }])
      await expect(
        runSettingsMigrations({
          options: { type: 'mysql', ...options },
          runMigrations,
        } as unknown as DataSource),
      ).rejects.toThrow(/forbidden/);
    expect(runMigrations).toHaveBeenCalledTimes(1);
  });
});

describe('public entry point and entity schema', () => {
  it('re-exports the store, factories, errors and schema', async () => {
    const api = await import('./index.js');
    expect(Object.keys(api).sort()).toEqual(
      expect.arrayContaining([
        'TypeOrmSettingsStore',
        'SettingsStoreError',
        'createSettingsDataSource',
        'createSettingsMigrationDataSource',
        'runSettingsMigrations',
        'CreateCompanySettings2026100600090',
        'SETTINGS_ENTITIES',
        'SETTINGS_TABLES',
      ]),
    );
  });
  it('exports one schema with a class target', () => {
    expect(SETTINGS_ENTITIES.map((schema) => schema.options.tableName)).toEqual(
      Object.values(SETTINGS_TABLES),
    );
    expect(SettingsEntity.name).toBe('SettingsEntity');
  });
});
